Repository OCA/sale-promotion, pull requests merged in 2022-05, with the labels that each got.

#51 [13.0][FIX] sale_coupon_limit: Lower development status
  sale_coupon_limit/__manifest__.py
Labels: bot is merging ⏳

#50 [13.0][FIX] sale_coupon_multiplier_free_product: wrong property
  sale_coupon_multiplier_free_product/models/sale_coupon.py
Labels: approved, bot is merging ⏳

#46 [13.0][IMP] sale_coupon_order_line_link: view applied promotions
  sale_coupon_order_line_link/__manifest__.py
  sale_coupon_order_line_link/views/sale_order_views.xml
Labels: approved, bot is merging ⏳

#9 [13.0][ADD] sale_coupon_incompatibility: New module
  sale_coupon_incompatibility/README.rst
  sale_coupon_incompatibility/__init__.py
  sale_coupon_incompatibility/__manifest__.py
  sale_coupon_incompatibility/models/__init__.py
  sale_coupon_incompatibility/models/sale_coupon.py
  sale_coupon_incompatibility/models/sale_coupon_program.py
  sale_coupon_incompatibility/readme/CONFIGURE.rst
  sale_coupon_incompatibility/readme/CONTRIBUTORS.rst
  sale_coupon_incompatibility/readme/DESCRIPTION.rst
  sale_coupon_incompatibility/readme/USAGE.rst
  sale_coupon_incompatibility/static/description/icon.png
  sale_coupon_incompatibility/static/description/icon.svg
  sale_coupon_incompatibility/static/description/index.html
  sale_coupon_incompatibility/tests/__init__.py
  sale_coupon_incompatibility/tests/test_sale_coupon_incompatibility.py
  sale_coupon_incompatibility/views/sale_coupon_program_views.xml
  setup/sale_coupon_incompatibility/odoo/addons/sale_coupon_incompatibility
  setup/sale_coupon_incompatibility/setup.py
Labels: approved, bot is merging ⏳

#52 [14.0][ADD] sale_coupon_delivery_auto_refresh
  oca_dependencies.txt
  sale_coupon_delivery_auto_refresh/README.rst
  sale_coupon_delivery_auto_refresh/__init__.py
  sale_coupon_delivery_auto_refresh/__manifest__.py
  sale_coupon_delivery_auto_refresh/models/__init__.py
  sale_coupon_delivery_auto_refresh/models/sale_order.py
  sale_coupon_delivery_auto_refresh/readme/CONFIGURE.rst
  sale_coupon_delivery_auto_refresh/readme/CONTRIBUTORS.rst
  sale_coupon_delivery_auto_refresh/readme/DESCRIPTION.rst
  sale_coupon_delivery_auto_refresh/readme/HISTORY.rst
  sale_coupon_delivery_auto_refresh/readme/USAGE.rst
  sale_coupon_delivery_auto_refresh/static/description/icon.png
  sale_coupon_delivery_auto_refresh/tests/__init__.py
  sale_coupon_delivery_auto_refresh/tests/test_sale_coupon_delivery_auto_refresh.py
  setup/sale_coupon_delivery_auto_refresh/odoo/addons/sale_coupon_delivery_auto_refresh
  setup/sale_coupon_delivery_auto_refresh/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#53 [14.0][MIG] sale_coupon_order_line_link: Migration to 14.0
  sale_coupon_order_line_link/README.rst
  sale_coupon_order_line_link/__init__.py
  sale_coupon_order_line_link/__manifest__.py
  sale_coupon_order_line_link/i18n/sale_coupon_order_line_link.pot
  sale_coupon_order_line_link/models/__init__.py
  sale_coupon_order_line_link/models/sale_order.py
  sale_coupon_order_line_link/readme/CONTRIBUTORS.rst
  sale_coupon_order_line_link/readme/DESCRIPTION.rst
  sale_coupon_order_line_link/readme/ROADMAP.rst
  sale_coupon_order_line_link/reports/__init__.py
  sale_coupon_order_line_link/reports/sale_report.py
  sale_coupon_order_line_link/reports/sale_report_views.xml
  sale_coupon_order_line_link/static/description/icon.png
  sale_coupon_order_line_link/static/description/index.html
  sale_coupon_order_line_link/tests/__init__.py
  sale_coupon_order_line_link/tests/test_coupon_order_line_link.py
  sale_coupon_order_line_link/views/sale_order_views.xml
  setup/sale_coupon_order_line_link/odoo/addons/sale_coupon_order_line_link
  setup/sale_coupon_order_line_link/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#59 [14.0][ADD] sale_coupon_reward_fixed_price
  sale_coupon_reward_fixed_price/README.rst
  sale_coupon_reward_fixed_price/__init__.py
  sale_coupon_reward_fixed_price/__manifest__.py
  sale_coupon_reward_fixed_price/models/__init__.py
  sale_coupon_reward_fixed_price/models/coupon_program.py
  sale_coupon_reward_fixed_price/models/coupon_reward.py
  sale_coupon_reward_fixed_price/models/sale_order.py
  sale_coupon_reward_fixed_price/readme/CONFIGURE.rst
  sale_coupon_reward_fixed_price/readme/CONTRIBUTORS.rst
  sale_coupon_reward_fixed_price/readme/CREDITS.rst
  sale_coupon_reward_fixed_price/readme/DESCRIPTION.rst
  sale_coupon_reward_fixed_price/readme/USAGE.rst
  sale_coupon_reward_fixed_price/static/description/icon.png
  sale_coupon_reward_fixed_price/tests/__init__.py
  sale_coupon_reward_fixed_price/tests/test_sale_coupon_fixed_price.py
  sale_coupon_reward_fixed_price/views/coupon_program_view.xml
  setup/sale_coupon_reward_fixed_price/odoo/addons/sale_coupon_reward_fixed_price
  setup/sale_coupon_reward_fixed_price/setup.py
Labels: approved, bot is merging ⏳

#58 [MIG] sale_coupon_delivery_auto_refresh: Migration to 13.0
  sale_coupon_delivery_auto_refresh/README.rst
  sale_coupon_delivery_auto_refresh/__init__.py
  sale_coupon_delivery_auto_refresh/__manifest__.py
  sale_coupon_delivery_auto_refresh/i18n/it.po
  sale_coupon_delivery_auto_refresh/i18n/sale_coupon_delivery_auto_refresh.pot
  sale_coupon_delivery_auto_refresh/models/__init__.py
  sale_coupon_delivery_auto_refresh/models/sale_order.py
  sale_coupon_delivery_auto_refresh/readme/CONFIGURE.rst
  sale_coupon_delivery_auto_refresh/readme/CONTRIBUTORS.rst
  sale_coupon_delivery_auto_refresh/readme/DESCRIPTION.rst
  sale_coupon_delivery_auto_refresh/readme/HISTORY.rst
  sale_coupon_delivery_auto_refresh/readme/USAGE.rst
  sale_coupon_delivery_auto_refresh/static/description/icon.png
  sale_coupon_delivery_auto_refresh/static/description/index.html
  sale_coupon_delivery_auto_refresh/tests/__init__.py
  sale_coupon_delivery_auto_refresh/tests/test_sale_coupon_delivery_auto_refresh.py
  setup/sale_coupon_delivery_auto_refresh/odoo/addons/sale_coupon_delivery_auto_refresh
  setup/sale_coupon_delivery_auto_refresh/setup.py
Labels: bot is merging ⏳

#54 [14.0][ADD] sale_coupon_sale_order_based
  sale_coupon_criteria_order_based/README.rst
  sale_coupon_criteria_order_based/__init__.py
  sale_coupon_criteria_order_based/__manifest__.py
  sale_coupon_criteria_order_based/models/__init__.py
  sale_coupon_criteria_order_based/models/coupon_coupon.py
  sale_coupon_criteria_order_based/models/coupon_program.py
  sale_coupon_criteria_order_based/models/coupon_rule.py
  sale_coupon_criteria_order_based/readme/CONTRIBUTORS.rst
  sale_coupon_criteria_order_based/readme/DESCRIPTION.rst
  sale_coupon_criteria_order_based/readme/USAGE.rst
  sale_coupon_criteria_order_based/static/description/icon.png
  sale_coupon_criteria_order_based/tests/__init__.py
  sale_coupon_criteria_order_based/tests/test_sale_coupon_criteria_order_based.py
  sale_coupon_criteria_order_based/views/coupon_program_view.xml
  setup/sale_coupon_criteria_order_based/odoo/addons/sale_coupon_criteria_order_based
  setup/sale_coupon_criteria_order_based/setup.py
Labels: approved, bot is merging ⏳

#60 [13.0][FIX] sale_coupon_multiplier_free_product: performance on large orders
  sale_coupon_multiplier_free_product/models/sale_order.py
  sale_coupon_multiplier_free_product/tests/test_website_sale_coupon_free_product.py
Labels: approved, bot is merging ⏳

#63 [14.0][IMP] sale_coupon_order_line_link: hook method for extra discounts
  sale_coupon_order_line_link/models/sale_order.py
Labels: approved, bot is merging ⏳
