Repository OCA/sale-promotion, pull requests merged in 2022-06, with the labels that each got.

#41 [ADD] sale_coupon_reward_add_product
  sale_coupon_reward_add_product/__init__.py
  sale_coupon_reward_add_product/__manifest__.py
  sale_coupon_reward_add_product/models/__init__.py
  sale_coupon_reward_add_product/models/coupon_coupon.py
  sale_coupon_reward_add_product/models/coupon_program.py
  sale_coupon_reward_add_product/models/coupon_reward.py
  sale_coupon_reward_add_product/models/sale_order.py
  sale_coupon_reward_add_product/readme/CONFIGURE.rst
  sale_coupon_reward_add_product/readme/CONTRIBUTORS.rst
  sale_coupon_reward_add_product/readme/DESCRIPTION.rst
  sale_coupon_reward_add_product/tests/__init__.py
  sale_coupon_reward_add_product/tests/test_sale.py
  sale_coupon_reward_add_product/views/coupon_program.xml
  setup/sale_coupon_reward_add_product/odoo/addons/sale_coupon_reward_add_product
  setup/sale_coupon_reward_add_product/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#64 [MIG] sale_coupon_domain_product_discount: Migration/refactor to 13.0
  sale_coupon_domain_product_discount/README.rst
  sale_coupon_domain_product_discount/__init__.py
  sale_coupon_domain_product_discount/__manifest__.py
  sale_coupon_domain_product_discount/models/__init__.py
  sale_coupon_domain_product_discount/models/coupon_program.py
  sale_coupon_domain_product_discount/models/coupon_reward.py
  sale_coupon_domain_product_discount/models/coupon_rule.py
  sale_coupon_domain_product_discount/models/sale_order.py
  sale_coupon_domain_product_discount/readme/CONTRIBUTORS.rst
  sale_coupon_domain_product_discount/readme/DESCRIPTION.rst
  sale_coupon_domain_product_discount/readme/USAGE.rst
  sale_coupon_domain_product_discount/static/description/icon.png
  sale_coupon_domain_product_discount/tests/__init__.py
  sale_coupon_domain_product_discount/tests/test_domain_product_discount.py
  sale_coupon_domain_product_discount/views/coupon_program_views.xml
  setup/sale_coupon_domain_product_discount/odoo/addons/sale_coupon_domain_product_discount
  setup/sale_coupon_domain_product_discount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#66 [MIG] sale_coupon_criteria_order_based: Migration to 13.0
  sale_coupon_criteria_order_based/README.rst
  sale_coupon_criteria_order_based/__init__.py
  sale_coupon_criteria_order_based/__manifest__.py
  sale_coupon_criteria_order_based/i18n/it.po
  sale_coupon_criteria_order_based/i18n/sale_coupon_criteria_order_based.pot
  sale_coupon_criteria_order_based/models/__init__.py
  sale_coupon_criteria_order_based/models/coupon_coupon.py
  sale_coupon_criteria_order_based/models/coupon_program.py
  sale_coupon_criteria_order_based/models/coupon_rule.py
  sale_coupon_criteria_order_based/readme/CONTRIBUTORS.rst
  sale_coupon_criteria_order_based/readme/DESCRIPTION.rst
  sale_coupon_criteria_order_based/readme/USAGE.rst
  sale_coupon_criteria_order_based/static/description/icon.png
  sale_coupon_criteria_order_based/static/description/index.html
  sale_coupon_criteria_order_based/tests/__init__.py
  sale_coupon_criteria_order_based/tests/test_sale_coupon_criteria_order_based.py
  sale_coupon_criteria_order_based/views/coupon_program_view.xml
  setup/sale_coupon_criteria_order_based/odoo/addons/sale_coupon_criteria_order_based
  setup/sale_coupon_criteria_order_based/setup.py
Labels: approved, bot is merging ⏳

#67 [13.0][IMP] sale_coupon_auto_refresh: configurable triggers
  sale_coupon_auto_refresh/README.rst
  sale_coupon_auto_refresh/models/sale_coupon_refresh_mixin.py
  sale_coupon_auto_refresh/models/sale_order.py
  sale_coupon_auto_refresh/readme/CONFIGURE.rst
  sale_coupon_auto_refresh/static/description/index.html
  sale_coupon_auto_refresh/tests/test_sale_coupon_auto_refresh.py
Labels: approved, ready to merge, bot is merging ⏳

#47 [14.0][ADD] sale_promotion_domain_product_discount
  sale_coupon_domain_product_discount/README.rst
  sale_coupon_domain_product_discount/__init__.py
  sale_coupon_domain_product_discount/__manifest__.py
  sale_coupon_domain_product_discount/models/__init__.py
  sale_coupon_domain_product_discount/models/coupon_program.py
  sale_coupon_domain_product_discount/models/coupon_reward.py
  sale_coupon_domain_product_discount/models/coupon_rule.py
  sale_coupon_domain_product_discount/models/sale_order.py
  sale_coupon_domain_product_discount/readme/CONTRIBUTORS.rst
  sale_coupon_domain_product_discount/readme/DESCRIPTION.rst
  sale_coupon_domain_product_discount/readme/USAGE.rst
  sale_coupon_domain_product_discount/static/description/icon.png
  sale_coupon_domain_product_discount/tests/__init__.py
  sale_coupon_domain_product_discount/tests/test_domain_product_discount.py
  sale_coupon_domain_product_discount/views/coupon_program_views.xml
  setup/sale_coupon_domain_product_discount/odoo/addons/sale_coupon_domain_product_discount
  setup/sale_coupon_domain_product_discount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#68 [MIG] sale_coupon_criteria_multi_product: Migration to 14.0
  sale_coupon_criteria_multi_product/README.rst
  sale_coupon_criteria_multi_product/__init__.py
  sale_coupon_criteria_multi_product/__manifest__.py
  sale_coupon_criteria_multi_product/i18n/sale_coupon_criteria_multi_product.pot
  sale_coupon_criteria_multi_product/migrations/14.0.1.0.0/pre-migration.py
  sale_coupon_criteria_multi_product/models/__init__.py
  sale_coupon_criteria_multi_product/models/coupon_program.py
  sale_coupon_criteria_multi_product/models/sale_coupon_criteria.py
  sale_coupon_criteria_multi_product/readme/CONFIGURE.rst
  sale_coupon_criteria_multi_product/readme/CONTRIBUTORS.rst
  sale_coupon_criteria_multi_product/readme/DESCRIPTION.rst
  sale_coupon_criteria_multi_product/readme/USAGE.rst
  sale_coupon_criteria_multi_product/security/ir.model.access.csv
  sale_coupon_criteria_multi_product/static/description/icon.png
  sale_coupon_criteria_multi_product/static/description/icon.svg
  sale_coupon_criteria_multi_product/static/description/index.html
  sale_coupon_criteria_multi_product/tests/__init__.py
  sale_coupon_criteria_multi_product/tests/test_sale_coupon_criteria_multi_product.py
  sale_coupon_criteria_multi_product/views/sale_coupon_program_views.xml
  setup/sale_coupon_criteria_multi_product/odoo/addons/sale_coupon_criteria_multi_product
  setup/sale_coupon_criteria_multi_product/setup.py
Labels: approved, bot is merging ⏳

#42 [13.0][FIX] sale_coupon_multi_gift: mixed rewards
  sale_coupon_multi_gift/__manifest__.py
  sale_coupon_multi_gift/migrations/13.0.3.0.0/post-migrate.py
  sale_coupon_multi_gift/models/sale_order.py
  sale_coupon_multi_gift/tests/test_sale_coupon_multi_gift.py
Labels: bot is merging ⏳
