Repository OCA/sale-promotion, pull requests merged in 2023-11, with the labels that each got.

#172 [15.0][FIX] sale_coupon_domain_product_discount, coupon_domain_product_discount: Fix migration
  coupon_domain_product_discount/README.rst
  coupon_domain_product_discount/__manifest__.py
  coupon_domain_product_discount/models/__init__.py
  coupon_domain_product_discount/static/description/index.html
  sale_coupon_domain_product_discount/README.rst
  sale_coupon_domain_product_discount/__manifest__.py
  sale_coupon_domain_product_discount/models/__init__.py
  sale_coupon_domain_product_discount/models/coupon_program.py
  sale_coupon_domain_product_discount/static/description/index.html
Labels: approved, bot is merging ⏳

#115 [13.0][ADD] sale_coupon_order_pending_commercial_partner: New module
  sale_coupon_order_pending_commercial_partner/README.rst
  sale_coupon_order_pending_commercial_partner/__init__.py
  sale_coupon_order_pending_commercial_partner/__manifest__.py
  sale_coupon_order_pending_commercial_partner/models/__init__.py
  sale_coupon_order_pending_commercial_partner/models/sale_order.py
  sale_coupon_order_pending_commercial_partner/readme/CONTRIBUTORS.rst
  sale_coupon_order_pending_commercial_partner/readme/DESCRIPTION.rst
  sale_coupon_order_pending_commercial_partner/static/description/icon.png
  sale_coupon_order_pending_commercial_partner/static/description/index.html
  sale_coupon_order_pending_commercial_partner/tests/__init__.py
  sale_coupon_order_pending_commercial_partner/tests/test_sale_coupon_order_pending_commercial_partner.py
  setup/sale_coupon_order_pending_commercial_partner/odoo/addons/sale_coupon_order_pending_commercial_partner
  setup/sale_coupon_order_pending_commercial_partner/setup.py
Labels: bot is merging ⏳, stale

#174 [16.0][FIX] loyalty_partner_applicability: add res_config_settings to init models
  loyalty_partner_applicability/models/__init__.py
Labels: approved, bot is merging ⏳

#176 [16.0][MIG] coupon_mass_mailing > loyalty_mass_mailing: Renamed to loyalty_mass_mailing + Migration to version 16.0
  loyalty_mass_mailing/README.rst
  loyalty_mass_mailing/__init__.py
  loyalty_mass_mailing/__manifest__.py
  loyalty_mass_mailing/i18n/coupon_mass_mailing.pot
  loyalty_mass_mailing/i18n/es.po
  loyalty_mass_mailing/models/__init__.py
  loyalty_mass_mailing/models/loyalty_program.py
  loyalty_mass_mailing/models/mailing_mailing.py
  loyalty_mass_mailing/readme/CONTRIBUTORS.rst
  loyalty_mass_mailing/readme/DESCRIPTION.rst
  loyalty_mass_mailing/static/description/icon.png
  loyalty_mass_mailing/static/description/index.html
  loyalty_mass_mailing/tests/__init__.py
  loyalty_mass_mailing/tests/test_loyalty_mass_mailing.py
  loyalty_mass_mailing/views/loyalty_program_view.xml
  loyalty_mass_mailing/views/mailing_mailing_view.xml
  setup/loyalty_mass_mailing/odoo/addons/loyalty_mass_mailing
  setup/loyalty_mass_mailing/setup.py
Labels: approved, bot is merging ⏳

#164 [16.0][ADD] sale_loyalty_partner_applicability: New module
  sale_loyalty_partner_applicability/README.rst
  sale_loyalty_partner_applicability/__init__.py
  sale_loyalty_partner_applicability/__manifest__.py
  sale_loyalty_partner_applicability/models/__init__.py
  sale_loyalty_partner_applicability/models/sale_order.py
  sale_loyalty_partner_applicability/readme/CONFIGURE.rst
  sale_loyalty_partner_applicability/readme/CONTRIBUTORS.rst
  sale_loyalty_partner_applicability/readme/DESCRIPTION.rst
  sale_loyalty_partner_applicability/readme/USAGE.rst
  sale_loyalty_partner_applicability/static/description/index.html
  sale_loyalty_partner_applicability/tests/__init__.py
  sale_loyalty_partner_applicability/tests/test_sale_loyalty_partner_applicability.py
  sale_loyalty_partner_applicability/views/res_config_settings.xml
  setup/sale_loyalty_partner_applicability/odoo/addons/sale_loyalty_partner_applicability
  setup/sale_loyalty_partner_applicability/setup.py
Labels: bot is merging ⏳

#168 [16.0][ADD] sale_loyalty_initial_date_validity: New module
  sale_loyalty_initial_date_validity/README.rst
  sale_loyalty_initial_date_validity/__init__.py
  sale_loyalty_initial_date_validity/__manifest__.py
  sale_loyalty_initial_date_validity/i18n/sale_loyalty_initial_date_validity.pot
  sale_loyalty_initial_date_validity/models/__init__.py
  sale_loyalty_initial_date_validity/models/sale_order.py
  sale_loyalty_initial_date_validity/readme/CONTEXT.rst
  sale_loyalty_initial_date_validity/readme/CONTRIBUTORS.rst
  sale_loyalty_initial_date_validity/readme/DESCRIPTION.rst
  sale_loyalty_initial_date_validity/readme/ROADMAP.rst
  sale_loyalty_initial_date_validity/readme/USAGE.rst
  sale_loyalty_initial_date_validity/static/description/index.html
  sale_loyalty_initial_date_validity/tests/__init__.py
  sale_loyalty_initial_date_validity/tests/test_sale_loyalty_initial_date_validity.py
  setup/sale_loyalty_initial_date_validity/odoo/addons/sale_loyalty_initial_date_validity
  setup/sale_loyalty_initial_date_validity/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#155 [16.0][MIG] coupon_limit > loyalty_limit: Migration to version 16.0
  loyalty_limit/README.rst
  loyalty_limit/__init__.py
  loyalty_limit/__manifest__.py
  loyalty_limit/i18n/loyalty_limit.pot
  loyalty_limit/migrations/16.0.1.0.0/pre-migration.py
  loyalty_limit/models/__init__.py
  loyalty_limit/models/loyalty_program.py
  loyalty_limit/readme/CONTRIBUTORS.rst
  loyalty_limit/readme/DESCRIPTION.rst
  loyalty_limit/security/ir.model.access.csv
  loyalty_limit/static/description/icon.png
  loyalty_limit/static/description/icon.svg
  loyalty_limit/static/description/index.html
  loyalty_limit/tests/__init__.py
  loyalty_limit/tests/test_loyalty_limit.py
  loyalty_limit/views/loyalty_program_views.xml
  setup/loyalty_limit/odoo/addons/loyalty_limit
  setup/loyalty_limit/setup.py
Labels: approved, bot is merging ⏳

#178 [16.0][FIX] sale_loyalty_partner_applicability: correct domain evaluation
  sale_loyalty_partner_applicability/models/sale_order.py
Labels: approved, bot is merging ⏳

#154 [16.0][MIG] sale_coupon_partner > sale_loyalty_partner: Migration to version 16.0
  sale_loyalty_partner/README.rst
  sale_loyalty_partner/__init__.py
  sale_loyalty_partner/__manifest__.py
  sale_loyalty_partner/i18n/sale_coupon_partner.pot
  sale_loyalty_partner/models/__init__.py
  sale_loyalty_partner/models/loyalty_program.py
  sale_loyalty_partner/readme/CONTRIBUTORS.rst
  sale_loyalty_partner/readme/DESCRIPTION.rst
  sale_loyalty_partner/reports/__init__.py
  sale_loyalty_partner/reports/sale_report.py
  sale_loyalty_partner/reports/sale_report_views.xml
  sale_loyalty_partner/static/description/icon.png
  sale_loyalty_partner/static/description/index.html
  sale_loyalty_partner/views/sale_loyalty_program_views.xml
  setup/sale_loyalty_partner/odoo/addons/sale_loyalty_partner
  setup/sale_loyalty_partner/setup.py
Labels: bot is merging ⏳

#156 [16.0][MIG] sale_coupon_limit > sale_loyalty_limit: Migration to version 16.0
  sale_loyalty_limit/README.rst
  sale_loyalty_limit/__init__.py
  sale_loyalty_limit/__manifest__.py
  sale_loyalty_limit/i18n/it.po
  sale_loyalty_limit/i18n/sale_coupon_limit.pot
  sale_loyalty_limit/models/__init__.py
  sale_loyalty_limit/models/loyalty_program.py
  sale_loyalty_limit/models/sale_order.py
  sale_loyalty_limit/readme/CONFIGURE.rst
  sale_loyalty_limit/readme/CONTRIBUTORS.rst
  sale_loyalty_limit/readme/DESCRIPTION.rst
  sale_loyalty_limit/readme/USAGE.rst
  sale_loyalty_limit/security/ir.model.access.csv
  sale_loyalty_limit/static/description/icon.png
  sale_loyalty_limit/static/description/icon.svg
  sale_loyalty_limit/static/description/index.html
  sale_loyalty_limit/tests/__init__.py
  sale_loyalty_limit/tests/test_sale_loyalty_limit.py
  setup/sale_loyalty_limit/odoo/addons/sale_loyalty_limit
  setup/sale_loyalty_limit/setup.py
Labels: approved, bot is merging ⏳

#183 [15.0][FIX] sale_coupon_criteria_multi_product: Add security permissions to sales groups
  sale_coupon_criteria_multi_product/README.rst
  sale_coupon_criteria_multi_product/__manifest__.py
  sale_coupon_criteria_multi_product/security/ir.model.access.csv
  sale_coupon_criteria_multi_product/static/description/index.html
Labels: approved, bot is merging ⏳
