Repository OCA/sale-promotion, pull requests merged in 2023-06, with the labels that each got.

#138 [15.0][MIG] sale_coupon_order_pending: Migration to version 15.0
  sale_coupon_order_pending/README.rst
  sale_coupon_order_pending/__init__.py
  sale_coupon_order_pending/__manifest__.py
  sale_coupon_order_pending/models/__init__.py
  sale_coupon_order_pending/models/coupon_coupon.py
  sale_coupon_order_pending/models/sale_order.py
  sale_coupon_order_pending/readme/CONTRIBUTORS.rst
  sale_coupon_order_pending/readme/DESCRIPTION.rst
  sale_coupon_order_pending/readme/USAGE.rst
  sale_coupon_order_pending/static/description/icon.png
  sale_coupon_order_pending/static/description/index.html
  sale_coupon_order_pending/tests/__init__.py
  sale_coupon_order_pending/tests/test_sale_coupon_order_pending.py
  sale_coupon_order_pending/views/coupon_coupon_views.xml
  sale_coupon_order_pending/views/sale_order_views.xml
  setup/sale_coupon_order_pending/odoo/addons/sale_coupon_order_pending
  setup/sale_coupon_order_pending/setup.py
Labels: approved, bot is merging ⏳

#136 [15.0][MIG] sale_coupon_promotion_generate_coupon: Migration to version 15.0
  coupon_promotion_generate_coupon/README.rst
  coupon_promotion_generate_coupon/__init__.py
  coupon_promotion_generate_coupon/__manifest__.py
  coupon_promotion_generate_coupon/models/__init__.py
  coupon_promotion_generate_coupon/models/coupon_program.py
  coupon_promotion_generate_coupon/readme/CONTRIBUTORS.rst
  coupon_promotion_generate_coupon/readme/DESCRIPTION.rst
  coupon_promotion_generate_coupon/readme/USAGE.rst
  coupon_promotion_generate_coupon/static/description/icon.png
  coupon_promotion_generate_coupon/static/description/index.html
  coupon_promotion_generate_coupon/tests/__init__.py
  coupon_promotion_generate_coupon/tests/test_coupon_promotion_generate_coupon.py
  coupon_promotion_generate_coupon/views/coupon_program_views.xml
  sale_coupon_promotion_generate_coupon/README.rst
  sale_coupon_promotion_generate_coupon/__init__.py
  sale_coupon_promotion_generate_coupon/__manifest__.py
  sale_coupon_promotion_generate_coupon/models/__init__.py
  sale_coupon_promotion_generate_coupon/models/coupon_program.py
  sale_coupon_promotion_generate_coupon/models/sale_order.py
  sale_coupon_promotion_generate_coupon/readme/CONTRIBUTORS.rst
  sale_coupon_promotion_generate_coupon/readme/DESCRIPTION.rst
  sale_coupon_promotion_generate_coupon/readme/USAGE.rst
  sale_coupon_promotion_generate_coupon/static/description/icon.png
  sale_coupon_promotion_generate_coupon/static/description/index.html
  sale_coupon_promotion_generate_coupon/tests/__init__.py
  sale_coupon_promotion_generate_coupon/tests/test_sale_coupon_promotion_generate_coupon.py
  setup/coupon_promotion_generate_coupon/odoo/addons/coupon_promotion_generate_coupon
  setup/coupon_promotion_generate_coupon/setup.py
  setup/sale_coupon_promotion_generate_coupon/odoo/addons/sale_coupon_promotion_generate_coupon
  setup/sale_coupon_promotion_generate_coupon/setup.py
Labels: approved, bot is merging ⏳

#105 [13.0][ADD] sale_coupon_commercial_partner_applicability: New module
  sale_coupon_commercial_partner_applicability/README.rst
  sale_coupon_commercial_partner_applicability/__init__.py
  sale_coupon_commercial_partner_applicability/__manifest__.py
  sale_coupon_commercial_partner_applicability/models/__init__.py
  sale_coupon_commercial_partner_applicability/models/coupon_coupon.py
  sale_coupon_commercial_partner_applicability/readme/CONTRIBUTORS.rst
  sale_coupon_commercial_partner_applicability/readme/DESCRIPTION.rst
  sale_coupon_commercial_partner_applicability/static/description/icon.png
  sale_coupon_commercial_partner_applicability/static/description/index.html
  sale_coupon_commercial_partner_applicability/tests/__init__.py
  sale_coupon_commercial_partner_applicability/tests/test_sale_coupon_apply_commercial_partner.py
  setup/sale_coupon_commercial_partner_applicability/odoo/addons/sale_coupon_commercial_partner_applicability
  setup/sale_coupon_commercial_partner_applicability/setup.py
Labels: bot is merging ⏳

#116 [13.0][ADD] sale_coupon_portal_commercial_partner_applicability: New module to see your company coupons on portal view
  sale_coupon_portal_commercial_partner_applicability/README.rst
  sale_coupon_portal_commercial_partner_applicability/__init__.py
  sale_coupon_portal_commercial_partner_applicability/__manifest__.py
  sale_coupon_portal_commercial_partner_applicability/controllers/__init__.py
  sale_coupon_portal_commercial_partner_applicability/controllers/portal.py
  sale_coupon_portal_commercial_partner_applicability/readme/CONFIGURE.rst
  sale_coupon_portal_commercial_partner_applicability/readme/CONTRIBUTORS.rst
  sale_coupon_portal_commercial_partner_applicability/readme/DESCRIPTION.rst
  sale_coupon_portal_commercial_partner_applicability/readme/USAGE.rst
  sale_coupon_portal_commercial_partner_applicability/static/description/index.html
  setup/sale_coupon_portal_commercial_partner_applicability/odoo/addons/sale_coupon_portal_commercial_partner_applicability
  setup/sale_coupon_portal_commercial_partner_applicability/setup.py
Labels: bot is merging ⏳, stale
