Repository OCA/sale-promotion, pull requests merged in 2023-05, with the labels that each got.

#131 [15.0][MIG] sale_coupon_portal: Migration to version 15.0
  coupon_portal/README.rst
  coupon_portal/__init__.py
  coupon_portal/__manifest__.py
  coupon_portal/controllers/__init__.py
  coupon_portal/controllers/portal.py
  coupon_portal/i18n/coupon_portal.pot
  coupon_portal/i18n/es.po
  coupon_portal/readme/CONFIGURE.rst
  coupon_portal/readme/CONTRIBUTORS.rst
  coupon_portal/readme/DESCRIPTION.rst
  coupon_portal/readme/USAGE.rst
  coupon_portal/static/description/icon.svg
  coupon_portal/static/description/index.html
  coupon_portal/static/src/js/tour_coupon_portal.js
  coupon_portal/templates/coupon_portal_templates.xml
  coupon_portal/tests/__init__.py
  coupon_portal/tests/test_coupon_portal.py
  setup/coupon_portal/odoo/addons/coupon_portal
  setup/coupon_portal/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#133 [13.0][ADD] sale_coupon_financial_risk: New module
  sale_coupon_financial_risk/README.rst
  sale_coupon_financial_risk/__init__.py
  sale_coupon_financial_risk/__manifest__.py
  sale_coupon_financial_risk/models/__init__.py
  sale_coupon_financial_risk/models/sale_order.py
  sale_coupon_financial_risk/readme/CONTRIBUTORS.rst
  sale_coupon_financial_risk/readme/DESCRIPTION.rst
  sale_coupon_financial_risk/static/description/index.html
  sale_coupon_financial_risk/tests/__init__.py
  sale_coupon_financial_risk/tests/test_sale_coupon_financial_risk.py
  setup/sale_coupon_financial_risk/odoo/addons/sale_coupon_financial_risk
  setup/sale_coupon_financial_risk/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#132 [15.0][ADD] sale_coupon_validity_notification: New module
  sale_coupon_validity_notification/README.rst
  sale_coupon_validity_notification/__init__.py
  sale_coupon_validity_notification/__manifest__.py
  sale_coupon_validity_notification/i18n/es.po
  sale_coupon_validity_notification/i18n/sale_coupon_validity_notification.pot
  sale_coupon_validity_notification/models/__init__.py
  sale_coupon_validity_notification/models/coupon.py
  sale_coupon_validity_notification/readme/CONTRIBUTORS.rst
  sale_coupon_validity_notification/readme/DESCRIPTION.rst
  sale_coupon_validity_notification/readme/USAGE.rst
  sale_coupon_validity_notification/static/description/icon.png
  sale_coupon_validity_notification/static/description/index.html
  sale_coupon_validity_notification/tests/__init__.py
  sale_coupon_validity_notification/tests/test_sale_coupon_validity_notification.py
  setup/sale_coupon_validity_notification/odoo/addons/sale_coupon_validity_notification
  setup/sale_coupon_validity_notification/setup.py
Labels: approved, bot is merging ⏳

#135 [15.0][MIG] sale_coupon_financial_risk: Migration to version 15.0
  sale_coupon_financial_risk/README.rst
  sale_coupon_financial_risk/__init__.py
  sale_coupon_financial_risk/__manifest__.py
  sale_coupon_financial_risk/i18n/es.po
  sale_coupon_financial_risk/i18n/sale_coupon_financial_risk.pot
  sale_coupon_financial_risk/models/__init__.py
  sale_coupon_financial_risk/models/sale_order.py
  sale_coupon_financial_risk/readme/CONTRIBUTORS.rst
  sale_coupon_financial_risk/readme/DESCRIPTION.rst
  sale_coupon_financial_risk/static/description/icon.png
  sale_coupon_financial_risk/static/description/index.html
  sale_coupon_financial_risk/tests/__init__.py
  sale_coupon_financial_risk/tests/test_sale_coupon_financial_risk.py
  setup/sale_coupon_financial_risk/odoo/addons/sale_coupon_financial_risk
  setup/sale_coupon_financial_risk/setup.py
Labels: bot is merging ⏳

#137 [15.0][MIG] sale_coupon_commercial_partner_applicability: Renamed to coupon_commercial_partner_applicability + Migration to 15.0
  coupon_commercial_partner_applicability/README.rst
  coupon_commercial_partner_applicability/__init__.py
  coupon_commercial_partner_applicability/__manifest__.py
  coupon_commercial_partner_applicability/models/__init__.py
  coupon_commercial_partner_applicability/models/coupon_coupon.py
  coupon_commercial_partner_applicability/readme/CONTRIBUTORS.rst
  coupon_commercial_partner_applicability/readme/DESCRIPTION.rst
  coupon_commercial_partner_applicability/static/description/icon.png
  coupon_commercial_partner_applicability/static/description/index.html
  coupon_commercial_partner_applicability/tests/__init__.py
  coupon_commercial_partner_applicability/tests/test_sale_coupon_apply_commercial_partner.py
  setup/coupon_commercial_partner_applicability/odoo/addons/coupon_commercial_partner_applicability
  setup/coupon_commercial_partner_applicability/setup.py
Labels: approved, bot is merging ⏳
