Repository OCA/sale-promotion, pull requests merged in 2023-09, with the labels that each got.

#149 [16.0][MIG] website_sale_coupon_page > website_sale_loyalty_page: Migration to version 16.0
  setup/website_sale_loyalty_page/odoo/addons/website_sale_loyalty_page
  setup/website_sale_loyalty_page/setup.py
  website_sale_loyalty_page/README.rst
  website_sale_loyalty_page/__init__.py
  website_sale_loyalty_page/__manifest__.py
  website_sale_loyalty_page/controllers/__init__.py
  website_sale_loyalty_page/controllers/main.py
  website_sale_loyalty_page/i18n/es.po
  website_sale_loyalty_page/i18n/website_sale_coupon_page.pot
  website_sale_loyalty_page/models/__init__.py
  website_sale_loyalty_page/models/loyalty_program.py
  website_sale_loyalty_page/readme/CONFIGURE.rst
  website_sale_loyalty_page/readme/CONTRIBUTORS.rst
  website_sale_loyalty_page/readme/DESCRIPTION.rst
  website_sale_loyalty_page/readme/USAGE.rst
  website_sale_loyalty_page/static/description/icon.png
  website_sale_loyalty_page/static/description/index.html
  website_sale_loyalty_page/static/src/js/website_sale_loyalty_page_portal.js
  website_sale_loyalty_page/static/src/scss/styles.scss
  website_sale_loyalty_page/templates/promotion_templates.xml
  website_sale_loyalty_page/tests/__init__.py
  website_sale_loyalty_page/tests/test_website_sale_loyalty_page.py
  website_sale_loyalty_page/views/sale_loyalty_program_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#113 [13.0][ADD] sale_coupon_promotion_generate_coupon: New module
  sale_coupon_promotion_generate_coupon/README.rst
  sale_coupon_promotion_generate_coupon/__init__.py
  sale_coupon_promotion_generate_coupon/__manifest__.py
  sale_coupon_promotion_generate_coupon/models/__init__.py
  sale_coupon_promotion_generate_coupon/models/coupon_program.py
  sale_coupon_promotion_generate_coupon/models/sale_order.py
  sale_coupon_promotion_generate_coupon/readme/CONTRIBUTORS.rst
  sale_coupon_promotion_generate_coupon/readme/DESCRIPTION.rst
  sale_coupon_promotion_generate_coupon/readme/USAGE.rst
  sale_coupon_promotion_generate_coupon/static/description/icon.png
  sale_coupon_promotion_generate_coupon/static/description/index.html
  sale_coupon_promotion_generate_coupon/tests/__init__.py
  sale_coupon_promotion_generate_coupon/tests/test_sale_coupon_promotion_generate_coupon.py
  sale_coupon_promotion_generate_coupon/views/coupon_program_views.xml
  setup/sale_coupon_promotion_generate_coupon/odoo/addons/sale_coupon_promotion_generate_coupon
  setup/sale_coupon_promotion_generate_coupon/setup.py
Labels: bot is merging ⏳

#152 [16.0][MIG] sale_coupon_order_line_link > sale_loyalty_order_line_link: Migration to version 16.0
  sale_loyalty_order_line_link/README.rst
  sale_loyalty_order_line_link/__init__.py
  sale_loyalty_order_line_link/__manifest__.py
  sale_loyalty_order_line_link/i18n/it.po
  sale_loyalty_order_line_link/i18n/sale_coupon_order_line_link.pot
  sale_loyalty_order_line_link/migrations/16.0.1.0.0/pre-migration.py
  sale_loyalty_order_line_link/models/__init__.py
  sale_loyalty_order_line_link/models/sale_order.py
  sale_loyalty_order_line_link/readme/CONTRIBUTORS.rst
  sale_loyalty_order_line_link/readme/DESCRIPTION.rst
  sale_loyalty_order_line_link/readme/ROADMAP.rst
  sale_loyalty_order_line_link/reports/__init__.py
  sale_loyalty_order_line_link/reports/sale_report.py
  sale_loyalty_order_line_link/reports/sale_report_views.xml
  sale_loyalty_order_line_link/static/description/icon.png
  sale_loyalty_order_line_link/static/description/index.html
  sale_loyalty_order_line_link/tests/__init__.py
  sale_loyalty_order_line_link/tests/test_sale_loyalty_order_line_link.py
  sale_loyalty_order_line_link/views/sale_order_views.xml
  setup/sale_loyalty_order_line_link/odoo/addons/sale_loyalty_order_line_link
  setup/sale_loyalty_order_line_link/setup.py
Labels: approved, bot is merging ⏳
