Repository OCA/sale-promotion, pull requests merged in 2023-04, with the labels that each got.

#121 [15.0][MIG] sale_coupon_delivery_auto_refresh: Migration to version 15.0
  sale_coupon_delivery_auto_refresh/README.rst
  sale_coupon_delivery_auto_refresh/__init__.py
  sale_coupon_delivery_auto_refresh/__manifest__.py
  sale_coupon_delivery_auto_refresh/i18n/it.po
  sale_coupon_delivery_auto_refresh/i18n/sale_coupon_delivery_auto_refresh.pot
  sale_coupon_delivery_auto_refresh/models/__init__.py
  sale_coupon_delivery_auto_refresh/models/sale_order.py
  sale_coupon_delivery_auto_refresh/readme/CONFIGURE.rst
  sale_coupon_delivery_auto_refresh/readme/CONTRIBUTORS.rst
  sale_coupon_delivery_auto_refresh/readme/DESCRIPTION.rst
  sale_coupon_delivery_auto_refresh/readme/HISTORY.rst
  sale_coupon_delivery_auto_refresh/readme/USAGE.rst
  sale_coupon_delivery_auto_refresh/static/description/icon.png
  sale_coupon_delivery_auto_refresh/static/description/index.html
  sale_coupon_delivery_auto_refresh/tests/__init__.py
  sale_coupon_delivery_auto_refresh/tests/test_sale_coupon_delivery_auto_refresh.py
  setup/sale_coupon_delivery_auto_refresh/odoo/addons/sale_coupon_delivery_auto_refresh
  setup/sale_coupon_delivery_auto_refresh/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#107 [15.0][MIG] sale_coupon_selection_wizard: Migration to 15.0
  sale_coupon_selection_wizard/README.rst
  sale_coupon_selection_wizard/__init__.py
  sale_coupon_selection_wizard/__manifest__.py
  sale_coupon_selection_wizard/controllers/__init__.py
  sale_coupon_selection_wizard/controllers/main.py
  sale_coupon_selection_wizard/i18n/es.po
  sale_coupon_selection_wizard/i18n/sale_coupon_selection_wizard.pot
  sale_coupon_selection_wizard/models/__init__.py
  sale_coupon_selection_wizard/models/sale_order.py
  sale_coupon_selection_wizard/readme/CONTRIBUTORS.rst
  sale_coupon_selection_wizard/readme/DESCRIPTION.rst
  sale_coupon_selection_wizard/readme/USAGE.rst
  sale_coupon_selection_wizard/security/ir.model.access.csv
  sale_coupon_selection_wizard/static/description/icon.png
  sale_coupon_selection_wizard/static/description/index.html
  sale_coupon_selection_wizard/static/src/js/coupon_selection_wizard_mixin.js
  sale_coupon_selection_wizard/static/src/js/coupon_selection_wizard_view.js
  sale_coupon_selection_wizard/static/src/scss/coupon_selection_wizard.scss
  sale_coupon_selection_wizard/tests/__init__.py
  sale_coupon_selection_wizard/tests/test_sale_coupon_selection_wizard.py
  sale_coupon_selection_wizard/views/sale_order_views.xml
  sale_coupon_selection_wizard/views/templates.xml
  sale_coupon_selection_wizard/wizards/__init__.py
  sale_coupon_selection_wizard/wizards/coupon_selection_wizard.py
  sale_coupon_selection_wizard/wizards/coupon_selection_wizard_views.xml
  setup/sale_coupon_selection_wizard/odoo/addons/sale_coupon_selection_wizard
  setup/sale_coupon_selection_wizard/setup.py
Labels: approved, bot is merging ⏳

#109 [15.0][MIG] sale_coupon_order_suggestion: Migration to 15.0
  sale_coupon_order_suggestion/README.rst
  sale_coupon_order_suggestion/__init__.py
  sale_coupon_order_suggestion/__manifest__.py
  sale_coupon_order_suggestion/i18n/sale_coupon_order_suggestion.pot
  sale_coupon_order_suggestion/models/__init__.py
  sale_coupon_order_suggestion/models/sale_order.py
  sale_coupon_order_suggestion/readme/CONTRIBUTORS.rst
  sale_coupon_order_suggestion/readme/DESCRIPTION.rst
  sale_coupon_order_suggestion/readme/USAGE.rst
  sale_coupon_order_suggestion/static/description/icon.png
  sale_coupon_order_suggestion/static/description/index.html
  sale_coupon_order_suggestion/static/src/js/suggest_promotion_widget.esm.js
  sale_coupon_order_suggestion/static/src/js/suggest_promotion_widget_owl.esm.js
  sale_coupon_order_suggestion/static/src/xml/suggest_promotion.xml
  sale_coupon_order_suggestion/views/sale_order_views.xml
  setup/sale_coupon_order_suggestion/odoo/addons/sale_coupon_order_suggestion
  setup/sale_coupon_order_suggestion/setup.py
Labels: bot is merging ⏳

#111 [15.0][MIG] website_sale_coupon_selection_wizard: Migration to 15.0
  setup/website_sale_coupon_selection_wizard/odoo/addons/website_sale_coupon_selection_wizard
  setup/website_sale_coupon_selection_wizard/setup.py
  website_sale_coupon_selection_wizard/README.rst
  website_sale_coupon_selection_wizard/__init__.py
  website_sale_coupon_selection_wizard/__manifest__.py
  website_sale_coupon_selection_wizard/controllers/__init__.py
  website_sale_coupon_selection_wizard/controllers/coupon_page.py
  website_sale_coupon_selection_wizard/controllers/main.py
  website_sale_coupon_selection_wizard/controllers/promotion_wizard.py
  website_sale_coupon_selection_wizard/i18n/es.po
  website_sale_coupon_selection_wizard/i18n/website_sale_coupon_selection_wizard.pot
  website_sale_coupon_selection_wizard/readme/CONTRIBUTORS.rst
  website_sale_coupon_selection_wizard/readme/DESCRIPTION.rst
  website_sale_coupon_selection_wizard/readme/USAGE.rst
  website_sale_coupon_selection_wizard/static/description/icon.png
  website_sale_coupon_selection_wizard/static/description/index.html
  website_sale_coupon_selection_wizard/static/src/js/website_sale_coupon_selection_wizard.js
  website_sale_coupon_selection_wizard/static/src/scss/website_sale_coupon_selection.scss
  website_sale_coupon_selection_wizard/templates/promotion_templates.xml
Labels: bot is merging ⏳

#90 [14.0][FIX] sale_coupon_reward_fixed_price: Context for compatibility with sale_coupon_product_exclude
  sale_coupon_reward_fixed_price/models/sale_order.py
Labels: approved, bot is merging ⏳

#125 [14.0][MIG] sale_coupon_partner
  sale_coupon_partner/README.rst
  sale_coupon_partner/__init__.py
  sale_coupon_partner/__manifest__.py
  sale_coupon_partner/i18n/sale_coupon_partner.pot
  sale_coupon_partner/models/__init__.py
  sale_coupon_partner/models/sale_coupon_program.py
  sale_coupon_partner/readme/CONTRIBUTORS.rst
  sale_coupon_partner/readme/DESCRIPTION.rst
  sale_coupon_partner/reports/__init__.py
  sale_coupon_partner/reports/sale_report.py
  sale_coupon_partner/reports/sale_report_views.xml
  sale_coupon_partner/static/description/icon.png
  sale_coupon_partner/static/description/index.html
  sale_coupon_partner/tests/__init__.py
  sale_coupon_partner/tests/test_sale_coupon_partner.py
  sale_coupon_partner/views/sale_coupon_program_views.xml
  setup/sale_coupon_partner/odoo/addons/sale_coupon_partner
  setup/sale_coupon_partner/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#91 [14.0][IMP] sale_promotion_discount_if_field: compatibility with product exclude module
  sale_promotion_discount_in_field/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#120 [15.0][MIG] sale_coupon_multiplier_free_product: Migration to version 15.0
  coupon_multiplier_free_product/README.rst
  coupon_multiplier_free_product/__init__.py
  coupon_multiplier_free_product/__manifest__.py
  coupon_multiplier_free_product/models/__init__.py
  coupon_multiplier_free_product/models/coupon.py
  coupon_multiplier_free_product/models/coupon_program.py
  coupon_multiplier_free_product/models/coupon_reward.py
  coupon_multiplier_free_product/readme/CONFIGURE.rst
  coupon_multiplier_free_product/readme/CONTRIBUTORS.rst
  coupon_multiplier_free_product/readme/DESCRIPTION.rst
  coupon_multiplier_free_product/static/description/icon.png
  coupon_multiplier_free_product/static/description/index.html
  coupon_multiplier_free_product/tests/__init__.py
  coupon_multiplier_free_product/tests/test_coupon_multiplier_free_product.py
  coupon_multiplier_free_product/views/coupon_program_views.xml
  sale_coupon_multiplier_free_product/README.rst
  sale_coupon_multiplier_free_product/__init__.py
  sale_coupon_multiplier_free_product/__manifest__.py
  sale_coupon_multiplier_free_product/i18n/es.po
  sale_coupon_multiplier_free_product/i18n/sale_coupon_multiplier_free_product.pot
  sale_coupon_multiplier_free_product/models/__init__.py
  sale_coupon_multiplier_free_product/models/coupon_program.py
  sale_coupon_multiplier_free_product/models/sale_order.py
  sale_coupon_multiplier_free_product/readme/CONTRIBUTORS.rst
  sale_coupon_multiplier_free_product/readme/DESCRIPTION.rst
  sale_coupon_multiplier_free_product/readme/USAGE.rst
  sale_coupon_multiplier_free_product/static/description/icon.png
  sale_coupon_multiplier_free_product/static/description/index.html
  sale_coupon_multiplier_free_product/tests/__init__.py
  sale_coupon_multiplier_free_product/tests/test_sale_coupon_multiplier_free_product.py
  setup/coupon_multiplier_free_product/odoo/addons/coupon_multiplier_free_product
  setup/coupon_multiplier_free_product/setup.py
  setup/sale_coupon_multiplier_free_product/odoo/addons/sale_coupon_multiplier_free_product
  setup/sale_coupon_multiplier_free_product/setup.py
Labels: approved
