Repository OCA/sale-promotion, pull requests merged in 2025-07, with the labels that each got.

#286 [16.0][IMP] sale_loyalty_order_line_link: add a related so button
  sale_loyalty_order_line_link/README.rst
  sale_loyalty_order_line_link/__manifest__.py
  sale_loyalty_order_line_link/models/__init__.py
  sale_loyalty_order_line_link/models/loyalty_program.py
  sale_loyalty_order_line_link/readme/DESCRIPTION.rst
  sale_loyalty_order_line_link/static/description/index.html
  sale_loyalty_order_line_link/views/loyalty_program_views.xml
Labels: bot is merging ⏳

#259 [18.0][MIG] sale_loyalty_incompatibility: Migration to 18.0
  sale_loyalty_incompatibility/README.rst
  sale_loyalty_incompatibility/__init__.py
  sale_loyalty_incompatibility/__manifest__.py
  sale_loyalty_incompatibility/i18n/es.po
  sale_loyalty_incompatibility/i18n/it.po
  sale_loyalty_incompatibility/i18n/sale_loyalty_incompatibility.pot
  sale_loyalty_incompatibility/models/__init__.py
  sale_loyalty_incompatibility/models/sale_order.py
  sale_loyalty_incompatibility/pyproject.toml
  sale_loyalty_incompatibility/readme/CONTRIBUTORS.md
  sale_loyalty_incompatibility/readme/DESCRIPTION.md
  sale_loyalty_incompatibility/readme/USAGE.md
  sale_loyalty_incompatibility/static/description/icon.png
  sale_loyalty_incompatibility/static/description/icon.svg
  sale_loyalty_incompatibility/static/description/index.html
  sale_loyalty_incompatibility/tests/__init__.py
  sale_loyalty_incompatibility/tests/test_sale_coupon_incompatibility.py
Labels: approved, bot is merging ⏳

#211 [16.0][ADD] website_sale_loyalty_suggestion_wizard_multi_gift: New Module
  setup/website_sale_loyalty_suggestion_wizard_multi_gift/odoo/addons/website_sale_loyalty_suggestion_wizard_multi_gift
  setup/website_sale_loyalty_suggestion_wizard_multi_gift/setup.py
  website_sale_loyalty_suggestion_wizard/templates/wizard_templates.xml
  website_sale_loyalty_suggestion_wizard_multi_gift/README.rst
  website_sale_loyalty_suggestion_wizard_multi_gift/__init__.py
  website_sale_loyalty_suggestion_wizard_multi_gift/__manifest__.py
  website_sale_loyalty_suggestion_wizard_multi_gift/controllers/__init__.py
  website_sale_loyalty_suggestion_wizard_multi_gift/controllers/promotion_wizard.py
  website_sale_loyalty_suggestion_wizard_multi_gift/readme/CONTRIBUTORS.rst
  website_sale_loyalty_suggestion_wizard_multi_gift/readme/DESCRIPTION.rst
  website_sale_loyalty_suggestion_wizard_multi_gift/readme/USAGE.rst
  website_sale_loyalty_suggestion_wizard_multi_gift/static/description/icon.png
  website_sale_loyalty_suggestion_wizard_multi_gift/static/description/index.html
  website_sale_loyalty_suggestion_wizard_multi_gift/templates/wizard_templates.xml
Labels: approved, bot is merging ⏳, stale
